version: '3'
services:
  jenkins:
    image: test-jenkins-custom:1.0.0
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
    external: true
